### ISSUE TITLE
tcpblaster is using NuttX's CONFIG_ENDIAN_BIG for host OS program

### ISSUE THREAD

**Issue by yamt** [apache/incubator-nuttx-apps#150]

**Comment by Ouss4** [comment]
I guess we should remove the HTONS/L macros definition and replace them with htons/l (same as UDP blaster). The host implementation should worry about endianness.

**Comment by yamt** [comment]
@Ouss4 i agree. we need to adjust the usage as htons() is not usable in initializers on linux.
