### ISSUE TITLE
"make distclean" leaves a few auto generated Kconfig

### ISSUE THREAD

**Issue by yamt** [apache/incubator-nuttx-apps#539]
```
wireless/bluetooth/Kconfig:# This file is autogenerated, do not edit.
wireless/ieee802154/Kconfig:# This file is autogenerated, do not edit.
```

**Comment by Ouss4** [comment]
@yamt weren't these generated in a previous build?  By previous I mean several months ago before some changes were made to the build system, mainly Application.mk and Directory.mk.
Or maybe a manual clean was performed? maybe git clean -xdf?

The clean now doesn't recursively traverse all the directories in apps. It looks for .kconfig or .depend files.  If those files aren't there that directory won't be cleaned.

I just tried one config (esp32-devkitc:wapi) and the distclean deleted all the autogenerated files.

**Comment by yamt** [comment]
@Ouss4 thank you. probably it's the case as the tree was quite long-lived. i'll close this for now until i have a chance to confirm.
