### ISSUE TITLE
Compile MCUBOOT failed using mcuboot_agent config on esp32-wrover-kit

### ISSUE THREAD

**Issue by PierrePeng** [apache/incubator-nuttx-apps#947]
Hi @gustavonihei

I encouter to obstacle when I compile mcuboot using command as bellow. It seems that the configuration of compiler on NuttX uses C89 as default
`./tools/configure.sh esp32-wrover-kit:mcuboot_agent && make -j16`
![image](https://user-images.githubusercontent.com/23045104/147726706-311b824c-2f29-4f76-acd6-d18d1213ce70.png)

After I move the declarations out off for loop, I got multiple definition errors.
![image](https://user-images.githubusercontent.com/23045104/147726777-d1ddfc18-7d4f-49aa-85d9-cfb6b37053c1.png)

**Comment by gustavonihei** [comment]
Hi @PierrePeng.

> ./tools/configure.sh esp32-wrover-kit:mcuboot_agent && make -j16

The `esp32-devkitc:mcuboot_agent`, which is essentially equal to `esp32-wrover-kit:mcuboot_agent`, is part of the `incubator-nuttx` CI and it builds successfully using the `xtensa-esp32-elf-gcc` compiler from Espressif, which is the one assumed by the defconfig.
Could you please inform the version of the toolchain used to reproduce the issue?

If by any chance you modified the base `mcuboot_agent` defconfig, could you please share those changes?

**Comment by PierrePeng** [comment]
Hi @gustavonihei ,

Thanks for your reply! 
The version of `xtensa-esp32-elf-gcc` is shown below.  And I didn't modify the base `mcuboot_agent` deconfig.

![image](https://user-images.githubusercontent.com/23045104/147798099-6dafb403-e4dc-4585-b09f-18c774059ddf.png)

**Comment by PierrePeng** [comment]
@gustavonihei 

Now, I can compile successfully after I update the compiler to 8.4.0. 

Thanks!!!
